#If debug mode is active, the mod will log when items are dropped
debugMode = false
#Items to add, in the form modid:itemName:[nbtfile]:minStackSize:maxStackSize:universalChance:[monsterChance]:[bossChance]:[group1Chance]:[group2Chance]...
#Chances are %
#NBT File is a json file in the "editmobdrops" folder here in config (leave blank for none)
itemsToAdd = ["eventslootbags:common_lootbag::1:1:0:4:0", "eventslootbags:uncommon_lootbag::1:1:0:1:0", "eventslootbags:epic_lootbag::1:1:0:0:100", "eventslootbags:legendary_lootbag::1:1:0:0:15"]
#Mob groups, in the form [EntityModid]:[EntityName]:[EntityModid]:[EntityName]...
mobGroups = ["eventslootbags:common_lootbag::1:1:0:4:0", "eventslootbags:uncommon_lootbag::1:1:0:1:0", "eventslootbags:epic_lootbag::1:1:0:0:100", "eventslootbags:legendary_lootbag::1:1:0:0:15"]
#Mobs to clear existing drops from
mobsToClear = []
#Single mob items, in the form EntityModid:EntityName:modid:itemName:[nbtfile]:minStackSize:maxStackSize:chance
singleMobItems = ["minecraft:drowned:upgrade_aquatic:thrasher_tooth::1:2:10"]

